/*
 * This file is generated by jOOQ.
 */
package core.schema;


import core.schema.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Db extends SchemaImpl {

    private static final long serialVersionUID = -784340381;

    /**
     * The reference instance of <code>DB</code>
     */
    public static final Db DB = new Db();

    /**
     * The table <code>DB.account</code>.
     */
    public final Account ACCOUNT = core.schema.tables.Account.ACCOUNT;

    /**
     * The table <code>DB.account_asset</code>.
     */
    public final AccountAsset ACCOUNT_ASSET = core.schema.tables.AccountAsset.ACCOUNT_ASSET;

    /**
     * The table <code>DB.alias</code>.
     */
    public final Alias ALIAS = core.schema.tables.Alias.ALIAS;

    /**
     * The table <code>DB.alias_offer</code>.
     */
    public final AliasOffer ALIAS_OFFER = core.schema.tables.AliasOffer.ALIAS_OFFER;

    /**
     * The table <code>DB.ask_order</code>.
     */
    public final AskOrder ASK_ORDER = core.schema.tables.AskOrder.ASK_ORDER;

    /**
     * The table <code>DB.asset</code>.
     */
    public final Asset ASSET = core.schema.tables.Asset.ASSET;

    /**
     * The table <code>DB.asset_transfer</code>.
     */
    public final AssetTransfer ASSET_TRANSFER = core.schema.tables.AssetTransfer.ASSET_TRANSFER;

    /**
     * The table <code>DB.at</code>.
     */
    public final At AT = core.schema.tables.At.AT;

    /**
     * The table <code>DB.at_state</code>.
     */
    public final AtState AT_STATE = core.schema.tables.AtState.AT_STATE;

    /**
     * The table <code>DB.bid_order</code>.
     */
    public final BidOrder BID_ORDER = core.schema.tables.BidOrder.BID_ORDER;

    /**
     * The table <code>DB.block</code>.
     */
    public final Block BLOCK = core.schema.tables.Block.BLOCK;

    /**
     * The table <code>DB.escrow</code>.
     */
    public final Escrow ESCROW = core.schema.tables.Escrow.ESCROW;

    /**
     * The table <code>DB.escrow_decision</code>.
     */
    public final EscrowDecision ESCROW_DECISION = core.schema.tables.EscrowDecision.ESCROW_DECISION;

    /**
     * The table <code>DB.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = core.schema.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>DB.goods</code>.
     */
    public final Goods GOODS = core.schema.tables.Goods.GOODS;

    /**
     * The table <code>DB.indirect_incoming</code>.
     */
    public final IndirectIncoming INDIRECT_INCOMING = core.schema.tables.IndirectIncoming.INDIRECT_INCOMING;

    /**
     * The table <code>DB.peer</code>.
     */
    public final Peer PEER = core.schema.tables.Peer.PEER;

    /**
     * The table <code>DB.purchase</code>.
     */
    public final Purchase PURCHASE = core.schema.tables.Purchase.PURCHASE;

    /**
     * The table <code>DB.purchase_feedback</code>.
     */
    public final PurchaseFeedback PURCHASE_FEEDBACK = core.schema.tables.PurchaseFeedback.PURCHASE_FEEDBACK;

    /**
     * The table <code>DB.purchase_public_feedback</code>.
     */
    public final PurchasePublicFeedback PURCHASE_PUBLIC_FEEDBACK = core.schema.tables.PurchasePublicFeedback.PURCHASE_PUBLIC_FEEDBACK;

    /**
     * The table <code>DB.reward_recip_assign</code>.
     */
    public final RewardRecipAssign REWARD_RECIP_ASSIGN = core.schema.tables.RewardRecipAssign.REWARD_RECIP_ASSIGN;

    /**
     * The table <code>DB.subscription</code>.
     */
    public final Subscription SUBSCRIPTION = core.schema.tables.Subscription.SUBSCRIPTION;

    /**
     * The table <code>DB.trade</code>.
     */
    public final Trade TRADE = core.schema.tables.Trade.TRADE;

    /**
     * The table <code>DB.transaction</code>.
     */
    public final Transaction TRANSACTION = core.schema.tables.Transaction.TRANSACTION;

    /**
     * The table <code>DB.unconfirmed_transaction</code>.
     */
    public final UnconfirmedTransaction UNCONFIRMED_TRANSACTION = core.schema.tables.UnconfirmedTransaction.UNCONFIRMED_TRANSACTION;

    /**
     * No further instances allowed
     */
    private Db() {
        super("DB", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            AccountAsset.ACCOUNT_ASSET,
            Alias.ALIAS,
            AliasOffer.ALIAS_OFFER,
            AskOrder.ASK_ORDER,
            Asset.ASSET,
            AssetTransfer.ASSET_TRANSFER,
            At.AT,
            AtState.AT_STATE,
            BidOrder.BID_ORDER,
            Block.BLOCK,
            Escrow.ESCROW,
            EscrowDecision.ESCROW_DECISION,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Goods.GOODS,
            IndirectIncoming.INDIRECT_INCOMING,
            Peer.PEER,
            Purchase.PURCHASE,
            PurchaseFeedback.PURCHASE_FEEDBACK,
            PurchasePublicFeedback.PURCHASE_PUBLIC_FEEDBACK,
            RewardRecipAssign.REWARD_RECIP_ASSIGN,
            Subscription.SUBSCRIPTION,
            Trade.TRADE,
            Transaction.TRANSACTION,
            UnconfirmedTransaction.UNCONFIRMED_TRANSACTION);
    }
}
